Pull request #1 from teodoroven
ENAleksey/etis-extension pull request #9
Opened 2021-10-05 11:44 UTC by teodoroven

• Added row with total hours in teach plan page
• Added the trimester number parser into the course number + trimester 
number in teach plan page
• Fixed consultations button: now it remembers your choice in timetable 
page

2021-10-09 16:27 UTC, VladislavMaksimov requested changes

2021-10-09 16:27 UTC, VladislavMaksimov commented on scripts.js
> +		const tables = document.querySelectorAll('table.common');
В целом всё окей, но нужно кое-что исправить.

1. Ты вставляешь строку прямо в таблицу, чтобы её отобразить, браузер внутри каждой таблицы создаёт дополнительное tbody для этой строки. Это чревато неожиданными багами, и один из них в том, что у этой строки не отображается border. Нужно вставлять твою строку внутрь tbody. Если в этом селекторе написать table.common > tbody, по идее, всё должно сработать.

2021-10-09 16:27 UTC, VladislavMaksimov commented on scripts.js
> +			header.textContent += ` (${Math.floor(number / 3)+1} курс, ${(number-1) % 3 + 1} триместр)`; // Вычисляем номер курса и добавляем к заголовку
Номер курса в каждом третьем триместре считается неправильно.  Например, 3 / 3 + 1 = 1 + 1 = 2 ===> 3 триместр 1 курса становится 3 триместром 2 курса. 

Я предлагаю просто использовать Math.ceil вместо Math.floor, ну и соответственно убрать из расчёта курса +1.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil

2021-10-09 16:27 UTC, VladislavMaksimov commented on scripts.js
> +	      localStorage.setItem('showConsultations',String(!checkbox.checked));
Здесь чекбокс прыгает меняет состояние на предыдущее после нажатия. Кажется, надо кидать в локалсторейдж checkbox.checked, а не противоположное ему значение.

2021-10-09 16:27 UTC, VladislavMaksimov commented on scripts.js
> +	const button = document.querySelector('.timetable-btn.consultations');
Ну и последнее: добавь, плз, на всякий случай проверку того, что открыта страница с расписанием. Класс .consultations, наверное, действительно есть только в расписании, но это ж ЕТИС :) Он может внезапно вылезти на какой-то левой странице.

2021-10-10 13:18 UTC, teodoroven commented on scripts.js
> +		const tables = document.querySelectorAll('table.common');
Пофиксил

2021-10-10 14:35 UTC, teodoroven commented on scripts.js
> +			header.textContent += ` (${Math.floor(number / 3)+1} курс, ${(number-1) % 3 + 1} триместр)`; // Вычисляем номер курса и добавляем к заголовку
Пофиксил

2021-10-10 14:36 UTC, teodoroven commented on scripts.js
> +	      localStorage.setItem('showConsultations',String(!checkbox.checked));
Это актуально для onchange, но если использовать onclick, то обработчик срабатывает раньше, чем input меняет состояние checked, поэтому отрицание здесь к месту.

2021-10-10 14:37 UTC, teodoroven commented on scripts.js
> +	const button = document.querySelector('.timetable-btn.consultations');
Сделал

2026-04-26 14:29 UTC, closed without merging